import { ChampionData } from './types';

// API Configuration - Use DataDragon directly (supports CORS)
export const API_CONFIG = {
  DATA_DRAGON_BASE: 'https://ddragon.leagueoflegends.com',
  VERSIONS_URL: 'https://ddragon.leagueoflegends.com/api/versions.json',
  CHAMPION_DATA_URL: 'https://ddragon.leagueoflegends.com/cdn/{version}/data/en_US/champion.json',
  REQUEST_TIMEOUT: 10000, // Standard timeout
  RETRY_ATTEMPTS: 3,
  CACHE_DURATION: 1000 * 60 * 60, // 1 hour cache duration for champion data
} as const;

// UI Constants
export const UI_CONFIG = {
  WINDOW_WIDTH: 1280,
  WINDOW_HEIGHT: 800,
  MIN_WINDOW_WIDTH: 1024,
  MIN_WINDOW_HEIGHT: 600,
  GRID_COLUMNS: {
    DESKTOP: 8,
    TABLET: 6,
    MOBILE: 4,
  },
  CARD_SIZE: {
    WIDTH: 120,
    HEIGHT: 160,
  },
  DEBOUNCE_DELAY: 300,
} as const;

// Filter Configuration
export const FILTER_CONFIG = {
  ALL: 'all',
  OWNED: 'owned',
  MISSING: 'missing',
  SHARDS: 'shards',
  BOTH: 'both',
} as const;

// Theme Colors (duplicated from Tailwind config for JS usage)
export const THEME_COLORS = {
  BG_PRIMARY: '#0A0E1A',
  BG_SECONDARY: '#0A1428',
  GOLD: '#F0E6D2',
  GOLD_DARK: '#C89B3C',
  BLUE: '#0596AA',
  BLUE_LIGHT: '#0AC8B9',
  TEXT_PRIMARY: '#CDBE91',
  TEXT_SECONDARY: '#A09B8C',
} as const;

// Static champion data (fallback when API is unavailable)
export const STATIC_CHAMPIONS: ChampionData[] = [
  { id: 266, name: "Aatrox", title: "The Darkin Blade", iconUrl: "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/Aatrox.png" },
  { id: 103, name: "Ahri", title: "The Nine-Tailed Fox", iconUrl: "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/Ahri.png" },
  { id: 84, name: "Akali", title: "The Rogue Assassin", iconUrl: "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/Akali.png" },
  { id: 166, name: "Akshan", title: "The Rogue Sentinel", iconUrl: "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/Akshan.png" },
  { id: 12, name: "Alistar", title: "The Minotaur", iconUrl: "https://ddragon.leagueoflegends.com/cdn/14.1.1/img/champion/Alistar.png" },
  { id: 32, name: "Amumu", title: "The Sad Mummy" },
  { id: 34, name: "Anivia", title: "The Cryophoenix" },
  { id: 1, name: "Annie", title: "The Dark Child" },
  { id: 523, name: "Aphelios", title: "The Weapon of the Faithful" },
  { id: 22, name: "Ashe", title: "The Frost Archer" },
  { id: 136, name: "Aurelion Sol", title: "The Star Forger" },
  { id: 268, name: "Azir", title: "The Emperor of the Sands" },
  { id: 432, name: "Bard", title: "The Wandering Caretaker" },
  { id: 200, name: "Bel'Veth", title: "The Empress of the Void" },
  { id: 53, name: "Blitzcrank", title: "The Great Steam Golem" },
  { id: 63, name: "Brand", title: "The Burning Vengeance" },
  { id: 201, name: "Braum", title: "The Heart of the Freljord" },
  { id: 51, name: "Caitlyn", title: "The Sheriff of Piltover" },
  { id: 164, name: "Camille", title: "The Steel Shadow" },
  { id: 69, name: "Cassiopeia", title: "The Serpent's Embrace" },
  { id: 31, name: "Cho'Gath", title: "The Terror of the Void" },
  { id: 42, name: "Corki", title: "The Daring Bombardier" },
  { id: 122, name: "Darius", title: "The Hand of Noxus" },
  { id: 131, name: "Diana", title: "Scorn of the Moon" },
  { id: 119, name: "Draven", title: "The Glorious Executioner" },
  { id: 36, name: "Dr. Mundo", title: "The Madman of Zaun" },
  { id: 245, name: "Ekko", title: "The Boy Who Shattered Time" },
  { id: 60, name: "Elise", title: "The Spider Queen" },
  { id: 28, name: "Evelynn", title: "Agony's Embrace" },
  { id: 81, name: "Ezreal", title: "The Prodigal Explorer" },
  { id: 9, name: "Fiddlesticks", title: "The Ancient Fear" },
  { id: 114, name: "Fiora", title: "The Grand Duelist" },
  { id: 105, name: "Fizz", title: "The Tidal Trickster" },
  { id: 3, name: "Galio", title: "The Colossus" },
  { id: 41, name: "Gangplank", title: "The Saltwater Scourge" },
  { id: 86, name: "Garen", title: "The Might of Demacia" },
  { id: 150, name: "Gnar", title: "The Missing Link" },
  { id: 79, name: "Gragas", title: "The Rabble Rouser" },
  { id: 104, name: "Graves", title: "The Outlaw" },
  { id: 887, name: "Gwen", title: "The Hallowed Seamstress" },
  { id: 120, name: "Hecarim", title: "The Shadow of War" },
  { id: 74, name: "Heimerdinger", title: "The Revered Inventor" },
  { id: 420, name: "Illaoi", title: "The Kraken Priestess" },
  { id: 39, name: "Irelia", title: "The Blade Dancer" },
  { id: 427, name: "Ivern", title: "The Green Father" },
  { id: 40, name: "Janna", title: "The Storm's Fury" },
  { id: 59, name: "Jarvan IV", title: "The Exemplar of Demacia" },
  { id: 24, name: "Jax", title: "Grandmaster at Arms" },
  { id: 126, name: "Jayce", title: "The Defender of Tomorrow" },
  { id: 202, name: "Jhin", title: "The Virtuoso" },
  { id: 222, name: "Jinx", title: "The Loose Cannon" },
  { id: 145, name: "Kai'Sa", title: "Daughter of the Void" },
  { id: 429, name: "Kalista", title: "The Spear of Vengeance" },
  { id: 43, name: "Karma", title: "The Enlightened One" },
  { id: 30, name: "Karthus", title: "The Deathsinger" },
  { id: 38, name: "Kassadin", title: "The Void Walker" },
  { id: 55, name: "Katarina", title: "The Sinister Blade" },
  { id: 10, name: "Kayle", title: "The Righteous" },
  { id: 141, name: "Kayn", title: "The Shadow Reaper" },
  { id: 85, name: "Kennen", title: "The Heart of the Tempest" },
  { id: 121, name: "Kha'Zix", title: "The Voidreaver" },
  { id: 203, name: "Kindred", title: "The Eternal Hunters" },
  { id: 240, name: "Kled", title: "The Cantankerous Cavalier" },
  { id: 96, name: "Kog'Maw", title: "The Mouth of the Abyss" },
  { id: 897, name: "K'Sante", title: "The Pride of Nazumah" },
  { id: 7, name: "LeBlanc", title: "The Deceiver" },
  { id: 64, name: "Lee Sin", title: "The Blind Monk" },
  { id: 89, name: "Leona", title: "The Radiant Dawn" },
  { id: 876, name: "Lillia", title: "The Bashful Bloom" },
  { id: 127, name: "Lissandra", title: "The Ice Witch" },
  { id: 236, name: "Lucian", title: "The Purifier" },
  { id: 117, name: "Lulu", title: "The Fae Sorceress" },
  { id: 99, name: "Lux", title: "The Lady of Luminosity" },
  { id: 54, name: "Malphite", title: "Shard of the Monolith" },
  { id: 90, name: "Malzahar", title: "The Prophet of the Void" },
  { id: 57, name: "Maokai", title: "The Twisted Treant" },
  { id: 11, name: "Master Yi", title: "The Wuju Bladesman" },
  { id: 902, name: "Milio", title: "The Gentle Flame" },
  { id: 21, name: "Miss Fortune", title: "The Bounty Hunter" },
  { id: 62, name: "Wukong", title: "The Monkey King" },
  { id: 82, name: "Mordekaiser", title: "The Iron Revenant" },
  { id: 25, name: "Morgana", title: "The Fallen" },
  { id: 950, name: "Naafiri", title: "The Hound of a Hundred Bites" },
  { id: 267, name: "Nami", title: "The Tidecaller" },
  { id: 75, name: "Nasus", title: "The Curator of the Sands" },
  { id: 111, name: "Nautilus", title: "The Titan of the Depths" },
  { id: 518, name: "Neeko", title: "The Curious Chameleon" },
  { id: 76, name: "Nidalee", title: "The Bestial Huntress" },
  { id: 895, name: "Nilah", title: "The Joy Unbound" },
  { id: 56, name: "Nocturne", title: "The Eternal Nightmare" },
  { id: 20, name: "Nunu & Willump", title: "The Boy and His Yeti" },
  { id: 2, name: "Olaf", title: "The Berserker" },
  { id: 61, name: "Orianna", title: "The Lady of Clockwork" },
  { id: 516, name: "Ornn", title: "The Fire Beneath the Mountain" },
  { id: 80, name: "Pantheon", title: "The Unbreakable Spear" },
  { id: 78, name: "Poppy", title: "Keeper of the Hammer" },
  { id: 555, name: "Pyke", title: "The Bloodharbor Ripper" },
  { id: 246, name: "Qiyana", title: "Empress of the Elements" },
  { id: 133, name: "Quinn", title: "Demacia's Wings" },
  { id: 497, name: "Rakan", title: "The Charmer" },
  { id: 33, name: "Rammus", title: "The Armordillo" },
  { id: 421, name: "Rek'Sai", title: "The Void Burrower" },
  { id: 526, name: "Rell", title: "The Iron Maiden" },
  { id: 888, name: "Renata Glasc", title: "The Chem-Baroness" },
  { id: 58, name: "Renekton", title: "The Butcher of the Sands" },
  { id: 107, name: "Rengar", title: "The Pridestalker" },
  { id: 92, name: "Riven", title: "The Exile" },
  { id: 68, name: "Rumble", title: "The Mechanized Menace" },
  { id: 13, name: "Ryze", title: "The Rune Mage" },
  { id: 360, name: "Samira", title: "The Desert Rose" },
  { id: 113, name: "Sejuani", title: "Fury of the North" },
  { id: 235, name: "Senna", title: "The Redeemer" },
  { id: 147, name: "Seraphine", title: "The Starry-Eyed Songstress" },
  { id: 875, name: "Sett", title: "The Boss" },
  { id: 35, name: "Shaco", title: "The Demon Jester" },
  { id: 98, name: "Shen", title: "The Eye of Twilight" },
  { id: 102, name: "Shyvana", title: "The Half-Dragon" },
  { id: 27, name: "Singed", title: "The Mad Chemist" },
  { id: 14, name: "Sion", title: "The Undead Juggernaut" },
  { id: 15, name: "Sivir", title: "The Battle Mistress" },
  { id: 72, name: "Skarner", title: "The Crystal Vanguard" },
  { id: 37, name: "Sona", title: "Maven of the Strings" },
  { id: 16, name: "Soraka", title: "The Starchild" },
  { id: 50, name: "Swain", title: "The Noxian Grand General" },
  { id: 517, name: "Sylas", title: "The Unshackled" },
  { id: 134, name: "Syndra", title: "The Dark Sovereign" },
  { id: 223, name: "Tahm Kench", title: "The River King" },
  { id: 163, name: "Taliyah", title: "The Stoneweaver" },
  { id: 91, name: "Talon", title: "The Blade's Shadow" },
  { id: 44, name: "Taric", title: "The Shield of Valoran" },
  { id: 17, name: "Teemo", title: "The Swift Scout" },
  { id: 412, name: "Thresh", title: "The Chain Warden" },
  { id: 18, name: "Tristana", title: "The Yordle Gunner" },
  { id: 48, name: "Trundle", title: "The Troll King" },
  { id: 23, name: "Tryndamere", title: "The Barbarian King" },
  { id: 4, name: "Twisted Fate", title: "The Card Master" },
  { id: 29, name: "Twitch", title: "The Plague Rat" },
  { id: 77, name: "Udyr", title: "The Spirit Walker" },
  { id: 6, name: "Urgot", title: "The Dreadnought" },
  { id: 110, name: "Varus", title: "The Arrow of Retribution" },
  { id: 67, name: "Vayne", title: "The Night Hunter" },
  { id: 45, name: "Veigar", title: "The Tiny Master of Evil" },
  { id: 161, name: "Vel'Koz", title: "The Eye of the Void" },
  { id: 711, name: "Vex", title: "The Gloomist" },
  { id: 254, name: "Vi", title: "The Piltover Enforcer" },
  { id: 234, name: "Viego", title: "The Ruined King" },
  { id: 112, name: "Viktor", title: "The Machine Herald" },
  { id: 8, name: "Vladimir", title: "The Crimson Reaper" },
  { id: 106, name: "Volibear", title: "The Relentless Storm" },
  { id: 19, name: "Warwick", title: "The Uncaged Wrath of Zaun" },
  { id: 498, name: "Xayah", title: "The Rebel" },
  { id: 101, name: "Xerath", title: "The Magus Ascendant" },
  { id: 5, name: "Xin Zhao", title: "The Seneschal of Demacia" },
  { id: 157, name: "Yasuo", title: "The Unforgiven" },
  { id: 777, name: "Yone", title: "The Unforgotten" },
  { id: 83, name: "Yorick", title: "The Shepherd of Souls" },
  { id: 350, name: "Yuumi", title: "The Magical Cat" },
  { id: 154, name: "Zac", title: "The Secret Weapon" },
  { id: 238, name: "Zed", title: "The Master of Shadows" },
  { id: 221, name: "Zeri", title: "The Spark of Zaun" },
  { id: 115, name: "Ziggs", title: "The Hexplosives Expert" },
  { id: 26, name: "Zilean", title: "The Chronokeeper" },
  { id: 142, name: "Zoe", title: "The Aspect of Twilight" },
  { id: 143, name: "Zyra", title: "Rise of the Thorns" }
];

// Storage keys
export const STORAGE_KEYS = {
  COLLECTION: 'lol-skin-tracker-collection',
  CHAMPIONS: 'lol-skin-tracker-champions',
  SETTINGS: 'lol-skin-tracker-settings',
  LAST_UPDATE: 'lol-skin-tracker-last-update',
} as const;

// Application metadata
export const APP_INFO = {
  NAME: 'LoL Skin Tracker',
  VERSION: '3.0.0',
  DESCRIPTION: 'Track your League of Legends skin collection',
} as const;